title: Vadimus
email: stuart@stut.net
description: >- # this means to ignore newlines until "baseurl:"
  A place for me to flex and develop my writing muscle.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vadimus.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stut
github_username:  stut

permalink: /:title.html

keep_files: [".git"]

plugins:
  - jekyll-feed
